name: Pete Marshall
favicon: null
layout_spectrum: 0.99103
typography_spectrum: 0.8321931890677661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8c8c8c'
    - '#6b383f'
    - '#0092bf'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
