name: Pete Marshall
favicon: null
layout_spectrum: 0.14587506535463035
typography_spectrum: 0.8321931890677661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5359355786349624
  lightness: 0.36219881824217737
  saturation: 0.5912317396141589
  rhythmicContrast: 0.4099854277446866
purpose: []
